
import { User, Contact, Deal, Task, DealStage, TaskStatus } from './types';

export const USERS: User[] = [
  { id: 'user-1', name: 'ישראל ישראלי', email: 'israel@example.com' },
  { id: 'user-2', name: 'משה כהן', email: 'moshe@example.com' },
];

export const CONTACTS: Contact[] = [
  {
    id: 'contact-1',
    firstName: 'דנה',
    lastName: 'לוי',
    fullName: 'דנה לוי',
    email: 'dana.levi@techcorp.com',
    phone: '050-1234567',
    company: 'TechCorp',
    title: 'מנהלת שיווק',
    source: 'Inbound',
    status: 'Active',
    ownerId: 'user-1',
    tags: ['VIP', 'Tel Aviv'],
    notes: 'פגישה נקבעה לשבוע הבא.',
    createdAt: '2023-01-15T09:00:00Z',
    updatedAt: '2023-01-20T14:30:00Z',
  },
  {
    id: 'contact-2',
    firstName: 'אבי',
    lastName: 'גולן',
    fullName: 'אבי גולן',
    email: 'avi.golan@innovate.io',
    phone: '052-7654321',
    company: 'Innovate.io',
    title: 'מנכ"ל',
    source: 'Referral',
    status: 'New',
    ownerId: 'user-2',
    tags: ['Startup'],
    notes: '',
    createdAt: '2023-02-10T11:00:00Z',
    updatedAt: '2023-02-10T11:00:00Z',
  },
];

export const DEALS: Deal[] = [
  {
    id: 'deal-1',
    name: 'פרויקט CRM חדש',
    company: 'TechCorp',
    amount: 150000,
    currency: 'ILS',
    stage: DealStage.Proposal,
    probability: 60,
    expectedCloseDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
    ownerId: 'user-1',
    contactIds: ['contact-1'],
    priority: 'High',
    healthScore: 85,
    createdAt: '2023-02-01T10:00:00Z',
    updatedAt: '2023-03-10T12:00:00Z',
  },
  {
    id: 'deal-2',
    name: 'שדרוג מערכת BI',
    company: 'Innovate.io',
    amount: 75000,
    currency: 'ILS',
    stage: DealStage.Qualification,
    probability: 20,
    expectedCloseDate: new Date(Date.now() + 60 * 24 * 60 * 60 * 1000).toISOString(),
    ownerId: 'user-2',
    contactIds: ['contact-2'],
    priority: 'Medium',
    healthScore: 60,
    createdAt: '2023-02-20T15:00:00Z',
    updatedAt: '2023-03-05T18:00:00Z',
  },
  {
    id: 'deal-3',
    name: 'רישיונות תוכנה שנתיים',
    company: 'Global Solutions',
    amount: 25000,
    currency: 'ILS',
    stage: DealStage.ClosedWon,
    probability: 100,
    expectedCloseDate: '2023-03-01T23:59:59Z',
    ownerId: 'user-1',
    contactIds: [],
    priority: 'Low',
    createdAt: '2023-01-10T10:00:00Z',
    updatedAt: '2023-03-01T16:00:00Z',
  },
];

export const TASKS: Task[] = [
  {
    id: 'task-1',
    title: 'הכנת הצעת מחיר עבור TechCorp',
    dueDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    status: TaskStatus.InProgress,
    priority: 'High',
    assigneeId: 'user-1',
    relatedType: 'Deal',
    relatedId: 'deal-1',
    notes: 'יש לכלול את כל הפיצ\'רים שנדונו בפגישה האחרונה.',
    createdAt: '2023-03-10T13:00:00Z',
    updatedAt: '2023-03-11T09:00:00Z',
  },
  {
    id: 'task-2',
    title: 'Follow-up עם אבי גולן',
    dueDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    status: TaskStatus.ToDo,
    priority: 'Medium',
    assigneeId: 'user-2',
    relatedType: 'Contact',
    relatedId: 'contact-2',
    notes: 'לשאול לגבי התקדמות תהליך הבדיקה הפנימי.',
    createdAt: '2023-03-08T16:00:00Z',
    updatedAt: '2023-03-08T16:00:00Z',
  },
];
